
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftMULTIPLICARDIVABS ADMIRACION AMPERSAND AND AS BARRA BOOL BREAK CADENA CAPACITY CARACTER CHAR CLONE COMA COMENTARIO CONCATENARSTR CONTAINS CORCHETEDERECHO CORCHETEIZQUIERDO DECIMAL DIFERENTE DIV DOSPUNTOS ELSE ENTERO F64 FALSE FN I64 I64POW ID IF IGUAL IGUALIGUAL INSERT LEN LET LLAVEDERECHO LLAVEIZQUIERDO LOOP MAIN MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS MULTIPLICAR MUT NEW OR PARENTESISDERECHO PARENTESISIZQUIERDO PORCENTAJE PUNTO PUNTOCOMA PUSH REMOVE RETURN SQRT STRING STRUCT TIPORETURN TO_STRING TRUE USIZE WHAT WHILE WITH_CAPACITYexpresion : valor MAS valorvalor : ENTERO'
    
_lr_action_items = {'ENTERO':([0,4,],[3,3,]),'$end':([1,3,5,],[0,-2,-1,]),'MAS':([2,3,],[4,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'valor':([0,4,],[2,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> valor MAS valor','expresion',3,'p_expresion','Sintactico.py',20),
  ('valor -> ENTERO','valor',1,'p_valor','Sintactico.py',26),
]
